import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/src/styles/globals.scss";
import Header from "@/src/components/layout/header/page";
import Navbar from "@/src/components/layout/navbar/page";
import dynamic from "next/dynamic";
import NextAuthProvider from "../components/provider/authProvider";
import { ToastContainer } from "react-toastify";

const Footer = dynamic(() => import("@/src/components/layout/footer/page"));
const Instragram = dynamic(
  () => import("@/src/components/layout/Instragram/page")
);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <Header />
          <Navbar />
          {children}
          <Instragram />
          <Footer />
          <ToastContainer />
        </NextAuthProvider>
      </body>
    </html>
  );
}
