import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.scss";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import NextAuthProvider from "@/components/provider/authProvider";

import SubHeader from "@/components/layout/SubHeader/page";
import Navbar from "@/components/layout/Navbar/page";
import Instragram from "@/src/components/layout/Instragram/page";
import Footer from "@/components/layout/Footer/page";
import { AuthProvider } from "../components/context/authContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <AuthProvider>
            <SubHeader />
            <Navbar />
            {children}
            <Instragram />
            <Footer />
            <ToastContainer />
          </AuthProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
